#!/bin/bash
#Программа вывода страницы с информацией системе
TITLE="System information Report for $HOSTNAME" 
CURRENT_TIME=$(date + "%x %r %Z")
TIME_STAMP="Generated $CURRENT_DATE, by $USER"

cat << _EOF_
<html>
	<head>
		<title>$title</title>
 	</head>
	<body>
 		<h1>$title</h1>
		<p>TIME_STAMP</p>
	</body>
</html>
_EOF_
