#!/bin/bash
#Программа вывода страницы с информацией системе
#o#

title="System information Report for $HOSTNAME" 
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
	cat <<- _EOF_
	<h2>System uptime</h2>
	<pre>$(uptime)</pre>
	_EOF_
	return
}
report_disk_space () {
	cat <<- _EOF_
	<h2>Дисковое пространство</h2>
	<pre>$(df -h)</pre>
	_EOF_
	return
}
report_home_space () {
	cat <<- _EOF_
	<h2>Дисковое пространство /home/</h2>
	<pre>$(du -sh /home/*)</pre>
	_EOF_
	return
}

cat << _EOF_
<html>
	<head>
		<title>$title</title>
 	</head>
	<body>
 		<h1>$title</h1>
		<p>#$TIME_STAMP</p>
		$(report_uptime)
		$(report_disk_space)
		$(report_home_space)
	</body>
</html>
_EOF_
